### ISSUE TITLE
Using the incorrect name for an API key throws exception: call of reflect.Value.SetString on zero Value

### ISSUE THREAD

**Issue by codingo** [Ice3man543/subfinder#26]
When setting up API keys if you specify the wrong key value an ambiguous exception is thrown:

> ➜  subfinder git:(master) ./main --set-config **VirusTotalAPIKey**=<key>
> 
>    ____     __   _____         __       
>   / __/_ __/ /  / __(_)__  ___/ /__ ____
>  _\ \/ // / _ \/ _// / _ \/ _  / -_) __/
> /___/\_,_/_.__/_/ /_/_//_/\_,_/\__/_/   
>                                       
> 
> SubFinder v0.1.0 	  Made with ❤ by @Ice3man
> ==================================================
> panic: reflect: call of reflect.Value.SetString on zero Value
> 
> goroutine 1 [running]:
> reflect.flag.mustBeAssignable(0x0)
> 	/usr/lib/go-1.8/src/reflect/value.go:221 +0x195
> reflect.Value.SetString(0x0, 0x0, 0x0, 0xbfd7746e, 0x40)
> 	/usr/lib/go-1.8/src/reflect/value.go:1529 +0x21
> main.main()
> 	/opt/subfinder/main.go:89 +0x208
> ➜  subfinder git:(master) ./main --set-config VirustotalAPIKey=<key>
> 

Note the misspelling of VirusTotal (should be Virustotal for successful addition).

**Comment by Ice3man543** [comment]
That doesn't seems like an issue since reflect needs correct name to change values at run time. Also, the README.md document correctly states the names we need to modify. Any ideas?

**Comment by codingo** [comment]
I think updating this to show a more accurate exception would be the best move. If you don't put 2+2 together this can be confusing for the end user in its current form.
