### ISSUE TITLE
Error: character '<' looking for beginning of value during scans (scan still completes)

### ISSUE THREAD

**Issue by christopherowen** [Ice3man543/subfinder#39]
## What's the problem (or question)?
included in the output is the following string:

   error: invalid character '<' looking for beginning of value

## How can we reproduce the issue?
1.  install golang 1.10.2 in a debian system
2. go get github.com/Ice3man543/subfinder
3. $GOPATH/bin/subfinder -d reddit.com

before the domains are output, the error message presents itself.

**Comment by codingo** [comment]
Am I correct in assuming that results are still outputted at the duration of the scan and that this isn't throwing an exception?

**Comment by christopherowen** [comment]
correct

**Comment by codingo** [comment]
Although I haven't tested this yet I received the following over slack, looks to be a problem with master:

```
[anon:~]$ subfinder -d supershady.ru

   ____     __   _____         __
  / __/_ __/ /  / __(_)__  ___/ /__ ____
 _\ \/ // / _ \/ _// / _ \/ _  / -_) __/
/___/\_,_/_.__/_/ /_/_//_/\_,_/\__/_/


SubFinder v0.1.0       Made with ❤ by @Ice3man
==================================================


[-] Searching For Subdomains in Censys
[-] Searching For Subdomains in Crt.sh
[-] Searching For Subdomains in CertDB
[-] Searching For Subdomains in Certspotter
[-] Searching For Subdomains in Threatcrowd
[-] Searching For Subdomains in Findsubdomains
[-] Searching For Subdomains in DNSDumpster
[-] Searching For Subdomains in PassiveTotal
[-] Searching For Subdomains in PTRArchive
[-] Searching For Subdomains in Hackertarget
[-] Searching For Subdomains in Virustotal
[-] Searching For Subdomains in Securitytrails
[-] Searching For Subdomains in WaybackArchive
[-] Searching For Subdomains in ThreatMiner
[-] Searching For Subdomains in Riddler
[-] Searching For Subdomains in Netcraft
[-] Searching For Subdomains in Dnsdb
[-] Searching For Subdomains in Baidu
[-] Searching For Subdomains in Bing
[-] Searching For Subdomains in Ask

[+] Finding subdomains for : supershady.rupanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x123c71b]

goroutine 33 [running]:
github.com/Ice3man543/subfinder/libsubfinder/sources/riddler.Query(0xc42012c000, 0xc4200b6120)
    /Users/anon/go/src/github.com/Ice3man543/subfinder/libsubfinder/sources/riddler/riddler.go:56 +0x24b
created by github.com/Ice3man543/subfinder/libsubfinder/engines/passive.Discover
    /Users/anon/go/src/github.com/Ice3man543/subfinder/libsubfinder/engines/passive/passive.go:136 +0x824
```
